# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='group',
            field=models.ManyToManyField(related_name='destinations', to='main.User'),
        ),
    ]
